cmake_minimum_required(VERSION 3.0.2)
project(ptz_control)
find_package(catkin REQUIRED COMPONENTS rospy std_msgs inspection_interfaces)
catkin_package(CATKIN_DEPENDS rospy std_msgs inspection_interfaces)
catkin_install_python(PROGRAMS scripts/ptz_controller.py scripts/protected_ptz_controller.py scripts/full_auto_ptz_controller.py scripts/ptz_keyboard.py DESTINATION ${CATKIN_PACKAGE_BIN_DESTINATION})
